import ChamferedBorder from '../../components/box/ChamferedBorder';
import BodyBase from '../../components/text/BodyBase';
import SubHeading from '../../components/text/SubHeading';
import Title from '../../components/text/Title';
import SectionLayout from '../../ui/SectionLayout';
import WhyVen1 from '../../assets/WhyVen1.png';
import WhyVen2 from '../../assets/WhyVen2.png';
import BodySmall from '../../components/text/BodySmall';
import SubTitle from '../../components/text/SubTitle';

function WhyVenture() {
  return (
    <SectionLayout>
      <SubHeading extraClass={`uppercase`} tracking={`tracking-widest`}>
        why venture
      </SubHeading>
      <Title>
        Same problem, <span className="text-btext-3-dark">different asset</span>
      </Title>
      <BodyBase fontWeight={`font-normal`} extraClass={`tab:w-[70%] pt-2.5`}>
        The Fund is actively investing and has built a portfolio that includes some of the top
        Artificial Intelligence, Machine Learning, and Data Infrastructure companies in the world.
      </BodyBase>
      <div className="my-12 flex flex-col sm:flex-row items-center justify-normal gap-10">
        <ChamferedBorder
          borderColor="bg-border-primary"
          width="sm:w-1/2"
          borderRadius="rounded-xl"
          chamferedRadius="6"
        >
          <img
            src={WhyVen1}
            alt="why venture"
            className="chamfer-tr-6 w-full h sm:h-64 tab:h-96 rounded-xl"
          />
        </ChamferedBorder>
        <ChamferedBorder
          borderColor="bg-border-primary"
          width="sm:w-1/2"
          borderRadius="rounded-xl"
          chamferedRadius="6"
        >
          <img
            src={WhyVen2}
            alt="why venture"
            className="chamfer-tr-6 w-full h-80 sm:h-64 tab:h-96 rounded-xl"
          />
        </ChamferedBorder>
      </div>
      <SubTitle>
        Vast majority of returns accrue in the{' '}
        <span className="text-btext-3-dark">private markets</span>
      </SubTitle>
      <div className="mt-[25px] grid sm:grid-cols-2 items-start justify-normal gap-8 sm:gap-16">
        <BodySmall>
          With companies staying private longer, the vast majority of the returns from private tech
          has accrued to the private investors before the public offering. Plus, access is gated,
          with hefty tolls, by fund managers and growth equity firms, just as in the real estate
          private equity world.
        </BodySmall>
        <BodySmall>
          During the 90's and early 00's, companies like Amazon and Google went public relatively
          soon in their growth cycle, while companies today are waiting on average 10 years longer.
          The result: individual investors confined to the public markets are missing out on a
          substantial portion of the returns generated by the next generation of industry leaders.
        </BodySmall>
      </div>
    </SectionLayout>
  );
}

export default WhyVenture;
